slam_toolbox:
  ros__parameters:
    mode: mapping
    use_sim_time: true

    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan_throttled

    resolution: 0.05

    minimum_laser_range: 0.12
    max_laser_range: 3.5

    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 3.5

    map_update_interval: 1.0

    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2

    use_scan_matching: true
    do_loop_closing: true

    scan_queue_size: 50
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
